### ISSUE TITLE
Storage inefficiency

### ISSUE THREAD

**Issue by wlandau** [wlandau/workflowHelper#1]
Workflows generate three separate copies of each saved object: one in an RDS file in the `workflowHelper` cache or current working directory and two others in `remake`'s hidden `.remake` cache. When I tried sharing the names of objects across instances of remake, only one copy is retained in `.remake`, but that triggers unwanted rebuilds. Sticking to just a single copy in `.remake` also triggers unwanted rebuilds. (To enforce reproducibility, `remake` doesn't just simply load R objects from other sessions.) Removing the `.remake` cache between instances of `remake` would disable rebuilds in responses to change in the user's code. To bring it down to a single copy, I think I would have to give up on `remake` or make the user micromanage files, neither of which is desirable.

**Comment by jarad** [comment]
This really sounds like hard drive inefficiency.

**Comment by wlandau** [comment]
Correct. I changed issue's the title to reflect this.

**Comment by wlandau** [comment]
When `remake` supports nested functions, I can fix this. Nested functions will allow me to condense

```{r}
myAnalysis_myData.rds:
  command: saveRDS("CACHE/myAnalysis_myData..SAVE..")

myAnalysis_myData..SAVE..:
  command: myAnalysis(myData..LOAD..)

myData..LOAD..:
  command: readRDS("CACHE/myData.rds")
```

down to

```{r}
myAnalysis_myData.rds:
  command: saveRDS(myAnalysis(readRDS("CACHE/myData.rds")), "CACHE/myAnalysis_myData.rds")
```

**Comment by wlandau** [comment]
Now, parallelRemake and workflowHelper work with just a single instance of remake. See the (parallelism issue)[https://github.com/richfitz/remake/issues/84] of remake for a discussion.
