### ISSUE TITLE
Reduce verbosity

### ISSUE THREAD

**Issue by jarad** [wlandau/workflowHelper#4]
It would be nice to have less output. In particular, if everything is up to date, it would be nice to just have the message "Everything up to date." rather than, e.g. 

> Rscript -e 'remake::make("mse.pdf", remake_file = "remake.yml")'
> [  LOAD ] 
> [  READ ]                     |  # loading sources
> <  MAKE > mse.pdf
> [    OK ] poisson100
> [    OK ] normal100
> [    OK ] normal1000
> [    OK ] poisson100_lm
> [    OK ] normal100_lm
> [    OK ] normal1000_lm
> [    OK ] poisson100_glm
> [    OK ] normal100_glm
> [    OK ] normal1000_glm
> [    OK ] poisson100_lm_mse
> [    OK ] normal100_lm_mse
> [    OK ] normal1000_lm_mse
> [    OK ] poisson100_glm_mse
> [    OK ] normal100_glm_mse
> [    OK ] normal1000_glm_mse
> [    OK ] mse
> [    OK ] mse.pdf

at a minimum it would be nice to only see the [ BUILD ] lines. 

I see that remake::make has a verbose option. Ideally we would be able to pass this argument when running `make`.

**Comment by wlandau** [comment]
I tried `remake::make(..., verbose = FALSE)`, and it muted all the console output regardless of whether there were targets to build. For `workflowHelper` and `parallelRemake`, which use Makefiles, this is equivalent to `make > /dev/null 2>&1` versus simply `make`. So until `remake`'s verbosity switch is more flexible than all-or-nothing, I don't think it's worth adding this as a feature to `workflowHelper` or `parallelRemake`. You might post an issue to `remake` requesting an option to mute unbuilt targets only.

**Comment by wlandau** [comment]
Then again, `verbose` isn't the only argument we might want to pass on to `remake::make`. So as of now, you can pass arguments directly to `remake::make` (except for `target_names` and `remake_file`) using the `remake_args` argument to `plan_workflow`. The upshot is that you can turn off `remake` verbosity now with `plan_workflow(..., remake_args = list(verbose = F))`. This comes from`parallelRemake::write_makefile(..., remake_args = list(verbose = F))`.
