### ISSUE TITLE
Cannot use paste in argument to function

### ISSUE THREAD

**Issue by jarad** [wlandau/workflowHelper#6]
For a particular function to create a dataset, I wanted to use paste to construct the file names.  But this produces the error `Error in FUN(X[[i]], ...) : Unknown special function paste`.

The example below uses workflow.R and the source dummy.R:

workflow.R

```
library(workflowHelper)
sources = strings(dummy.R)
datasets = commands(
  my_data = dummy(file=paste("test",1:2,".csv"))
)
plan_workflow(sources, datasets=datasets)
```

dummy.R

```
dummy = function(file) {
  read.csv(file)
}
```

**Comment by wlandau** [comment]
See the [`remake` issue on nested functions](https://github.com/richfitz/remake/issues/86). I hope `remake` will support nested functions in the future, but until then, there is nothing `workflowHelper` can do.

**Comment by wlandau** [comment]
See the [`remake` nested function issue](https://github.com/richfitz/remake/issues/86). Unfortunately, `remake` cannot support nested functions, which is what is ostensibly causing the error. So if you really want `paste` to be part of the command, then you're out of luck. What I think you'll need to do is write 

Looking more closely, it seems like what you may want to do is call

```r
my_data = dummy(file = c("test 1 .csv", "test 2 .csv"))
```

in which case `remake` would also complain about an "unknown special function `c`", so we're still out of luck. 

What I think you would have to do is something like

```r
datasets = commands(
my_data = dummy(file1 = "test1.csv", file2 = "test2.csv")
)
```

**Comment by wlandau** [comment]
Another advantage to explicitly writing "test1.csv" and "test2.csv" is that these files will be explicitly registered as dependencies. If you write `paste("test",1:2,".csv")` as an argument, changes to the `csv` files won't trigger rebuilds downstream.

**Comment by jarad** [comment]
That's what I did.
